TestVariable_object:
    path: /TestVariable/fetch/{object_id}/{format}
    defaults: { _controller: concerto_panel.TestVariable_controller:objectAction, format: json }
    
TestVariable_by_test_collection:
    path: /TestVariable/Test/{test_id}/collection
    defaults: { _controller: concerto_panel.TestVariable_controller:collectionByTestAction }

TestVariable_parameters_collection:
    path: /TestVariable/Test/{test_id}/parameters/collection
    defaults: { _controller: concerto_panel.TestVariable_controller:parametersCollectionAction }
    
TestVariable_returns_collection:
    path: /TestVariable/Test/{test_id}/returns/collection
    defaults: { _controller: concerto_panel.TestVariable_controller:returnsCollectionAction }
    
TestVariable_branches_collection:
    path: /TestVariable/Test/{test_id}/branches/collection
    defaults: { _controller: concerto_panel.TestVariable_controller:branchesCollectionAction }
    
TestVariable_save:
    path: /TestVariable/{object_id}/save
    defaults: { _controller: concerto_panel.TestVariable_controller:saveAction }
    methods:  [POST]
    
TestVariable_delete:
    path: /TestVariable/{object_ids}/delete
    defaults: { _controller: concerto_panel.TestVariable_controller:deleteAction }
    methods:  [POST]