TestNode_object:
    path: /TestNode/fetch/{object_id}/{format}
    defaults: { _controller: concerto_panel.TestNode_controller:objectAction, format: json }
    
TestNode_collection:
    path: /TestNode/collection/{format}
    defaults: { _controller: concerto_panel.TestNode_controller:collectionAction, format: json }

TestNode_collection_by_flow_test:
    path: /TestNode/flow/{test_id}/collection
    defaults: { _controller: concerto_panel.TestNode_controller:collectionByFlowTestAction }
    
TestNode_delete:
    path: /TestNode/{object_ids}/delete
    defaults: { _controller: concerto_panel.TestNode_controller:deleteAction }
    methods:  [POST]
    
TestNode_save:
    path: /TestNode/{object_id}/save
    defaults: { _controller: concerto_panel.TestNode_controller:saveAction }
    methods:  [POST]