TestSessionLog_collection:
    path: /TestSessionLog/collection
    defaults: { _controller: concerto_panel.TestSessionLog_controller:collectionAction }
    
TestSessionLog_collection_by_test:
    path: /TestSessionLog/Test/{test_id}/collection
    defaults: { _controller: concerto_panel.TestSessionLog_controller:collectionByTestAction }
    
TestSessionLog_delete:
    path: /TestSessionLog/{object_ids}/delete
    defaults: { _controller: concerto_panel.TestSessionLog_controller:deleteAction }
    methods:  [POST]
    
TestSessionLog_clear:
    path: /TestSessionLog/Test/{test_id}/clear
    defaults: { _controller: concerto_panel.TestSessionLog_controller:clearAction }
    methods:  [POST]