User_object:
    path: /User/fetch/{object_id}/{format}
    defaults: { _controller: concerto_panel.User_controller:objectAction, format: json }

User_collection:
    path: /User/collection/{format}
    defaults: { _controller: concerto_panel.User_controller:collectionAction, format: json }

User_form: 
    path: /User/form/{action}
    defaults: { _controller: concerto_panel.User_controller:formAction, action: edit }
    
User_save:
    path: /User/{object_id}/save
    defaults: { _controller: concerto_panel.User_controller:saveAction }
    methods:  [POST]
    
User_delete:
    path: /User/{object_ids}/delete
    defaults: { _controller: concerto_panel.User_controller:deleteAction } 
    methods:  [POST]