index:
    path:  /admin
    defaults: { _controller: concerto_panel.panel_controller:indexAction }
    
breadcrumbs_template: 
    path: /admin/breadcrumbs
    defaults: { _controller: concerto_panel.panel_controller:breadcrumbsAction }
    
locale_change:
    path:  /admin/locale/{locale}
    defaults: { _controller: concerto_panel.panel_controller:changeLocaleAction }

login:
    path: /login
    defaults: { _controller: concerto_panel.panel_controller:loginAction }
    
login_check:
    path: /admin/login_check
    
logout:
    path: /admin/logout