TestWizardParam_object:
    path: /TestWizardParam/fetch/{object_id}/{format}
    defaults: { _controller: concerto_panel.TestWizardParam_controller:objectAction, format: json }
    
TestWizardParam_collection:
    path: /TestWizardParam/collection/{format}
    defaults: { _controller: concerto_panel.TestWizardParam_controller:collectionAction, format: json }

TestWizardParam_collection_by_wizard:
    path: /TestWizardParam/TestWizard/{wizard_id}/collection/{format}
    defaults: { _controller: concerto_panel.TestWizardParam_controller:collectionByWizardAction, format: json }
    
TestWizardParam_collection_by_wizard_and_type:
    path: /TestWizardParam/TestWizard/{wizard_id}/type/{type}/collection
    defaults: { _controller: concerto_panel.TestWizardParam_controller:collectionByWizardAndTypeAction }
    
TestWizardParam_delete:
    path: /TestWizardParam/{object_ids}/delete
    defaults: { _controller: concerto_panel.TestWizardParam_controller:deleteAction }
    methods:  [POST]
    
TestWizardParam_save:
    path: /TestWizardParam/{object_id}/save
    defaults: { _controller: concerto_panel.TestWizardParam_controller:saveAction }
    methods:  [POST]
    
TestWizardParam_clear:
    path: /TestWizardParam/TestWizard/{wizard_id}/clear
    defaults: { _controller: concerto_panel.TestWizardParam_controller:clearAction }
    methods:  [POST]