Dialog_rdoc:
    path:  /dialog/r_documentation_generation_help.html
    defaults: { _controller: concerto_panel.Dialog_controller:rDocumentationWindowAction }
    
Dialog_generic:
    path:  /dialog/{template_name}
    defaults: { _controller: concerto_panel.Dialog_controller:genericWindowAction }
    
Dialog_root:
    path:  /dialog/
    defaults: { _controller: concerto_panel.Dialog_controller:genericWindowAction }